### ISSUE TITLE
An error occurred while installing racc (1.6.2), and Bundler cannot continue.

### ISSUE THREAD

**Issue by vishnudas-bluefox** [c477y/adulttime_dl#3]
To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/unknown/.gem/extensions/x86_64-linux/3.3.0/racc-1.6.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/unknown/.gem/gems/racc-1.6.2 for inspection.
Results logged to /home/unknown/.gem/extensions/x86_64-linux/3.3.0/racc-1.6.2/gem_make.out

  /snap/ruby/323/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /snap/ruby/323/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
  /snap/ruby/323/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
  /snap/ruby/323/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /snap/ruby/323/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /snap/ruby/323/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /snap/ruby/323/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
  /home/unknown/.gem/gems/bundler-2.3.14/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /home/unknown/.gem/gems/bundler-2.3.14/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /home/unknown/.gem/gems/bundler-2.3.14/lib/bundler/source/rubygems.rb:204:in `install'
  /home/unknown/.gem/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/unknown/.gem/gems/bundler-2.3.14/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/unknown/.gem/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /home/unknown/.gem/gems/bundler-2.3.14/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /home/unknown/.gem/gems/bundler-2.3.14/lib/bundler/worker.rb:62:in `apply_func'
  /home/unknown/.gem/gems/bundler-2.3.14/lib/bundler/worker.rb:57:in `block in process_queue'
  <internal:kernel>:187:in `loop'
  /home/unknown/.gem/gems/bundler-2.3.14/lib/bundler/worker.rb:54:in `process_queue'
  /home/unknown/.gem/gems/bundler-2.3.14/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

**Comment by c477y** [comment]
Hey, can you use ruby version [3.1.2](https://github.com/c477y/adulttime_dl/blob/main/.ruby-version) instead? I would also recommend you use the [v0.3.0](https://github.com/c477y/adulttime_dl/tree/v0.3.0) branch to run the tool.
